# /*
#  Copyright Â© ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
# */
router:
  frontend:
    mailer_root:
      frontName: 'page'
  adminhtml:
    mailer_root:
      frontName: 'page'