##
#  Copyright Â© ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
system_config:
  tab:
    id: 'core_forum'
    label: 'Forum'
  sections:
    forum:
      label: 'Forum'
      tab: 'core_forum'
      scope: 'default|website|website_view'
      groups:
        country_options:
          label: 'Country Options'
          scope: 'default|website|website_view'
          fields:
            default_country:
              label: 'Default Country'
              type: 'select'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
              scope: 'default|website|website_view'
            allowed_countries:
              label: 'Allow Countries'
              type: 'multiselect'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
              scope: 'default|website|website_view'