##
#  Copyright Â© ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
router:
  frontend:
    theme_root:
      frontName: 'ui'
  adminhtml:
    theme_root:
      frontName: 'ui'